apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-app
spec:
  selector:
    matchLabels:
      app: posts-app
  template:
    metadata:
      labels:
        app: posts-app
    spec:
      containers:
      - name: posts-app
        image: asia-southeast1-docker.pkg.dev/arthetic/arthetic-images/posts-svc:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4000
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: posts-secret
                key: database_url
          - name: PORT
            value: "4000"
